-- Unmatched Exercises Log
-- Tracks exercises generated by AI that don't match any in our database
-- Used for improving the exercise library over time

CREATE TABLE IF NOT EXISTS unmatched_exercises (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The exercise name as generated by AI
  ai_exercise_name TEXT NOT NULL,

  -- Normalized/cleaned version for deduplication
  normalized_name TEXT NOT NULL,

  -- Context from AI (what muscles it targets, etc.)
  ai_context JSONB DEFAULT '{}',

  -- How many times this exercise has been generated
  occurrence_count INTEGER DEFAULT 1,

  -- Status for review
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'added', 'rejected', 'merged')),

  -- If merged into existing exercise, which one
  merged_into_exercise_id UUID REFERENCES exercises(id),

  -- If added as new exercise, the new exercise ID
  added_as_exercise_id UUID REFERENCES exercises(id),

  -- Admin notes
  notes TEXT,

  -- Timestamps
  first_seen_at TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ,

  -- Unique constraint on normalized name to prevent duplicates
  CONSTRAINT unique_normalized_name UNIQUE (normalized_name)
);

-- Index for finding pending reviews
CREATE INDEX IF NOT EXISTS idx_unmatched_status ON unmatched_exercises(status);

-- Index for finding most common unmatched exercises
CREATE INDEX IF NOT EXISTS idx_unmatched_count ON unmatched_exercises(occurrence_count DESC);

-- Function to upsert unmatched exercise (increment count if exists)
CREATE OR REPLACE FUNCTION log_unmatched_exercise(
  p_ai_name TEXT,
  p_normalized_name TEXT,
  p_context JSONB DEFAULT '{}'
) RETURNS UUID AS $$
DECLARE
  v_id UUID;
BEGIN
  INSERT INTO unmatched_exercises (ai_exercise_name, normalized_name, ai_context)
  VALUES (p_ai_name, p_normalized_name, p_context)
  ON CONFLICT (normalized_name) DO UPDATE
  SET
    occurrence_count = unmatched_exercises.occurrence_count + 1,
    last_seen_at = NOW(),
    ai_context = CASE
      WHEN unmatched_exercises.ai_context IS NULL THEN p_context
      ELSE unmatched_exercises.ai_context || p_context
    END
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$ LANGUAGE plpgsql;

-- RLS policies
ALTER TABLE unmatched_exercises ENABLE ROW LEVEL SECURITY;

-- Only service role can insert (from Edge Function)
-- This is handled by using service role key in Edge Function

-- Create a view for admin to see most requested exercises
CREATE OR REPLACE VIEW unmatched_exercises_summary AS
SELECT
  id,
  ai_exercise_name,
  normalized_name,
  occurrence_count,
  status,
  first_seen_at,
  last_seen_at,
  ai_context
FROM unmatched_exercises
WHERE status = 'pending'
ORDER BY occurrence_count DESC, last_seen_at DESC;
